### ISSUE TITLE
大家来聊聊机器要怎么控制吧

### ISSUE THREAD

**Issue by tripack45** [MICF-JI204/SocMain#24]
通信方式是啥？蓝牙？wifi？红外？或者其他的东西？
操作终端是啥？电脑？手机？Pad？遥控器？PS2手柄？其他？

**Comment by zhaoccjj** [comment]
我试试邮件reply directly能不能管用.

发自我的 iPhone

**Comment by zhaoccjj** [comment]
PS2 蓝牙功能足够了吧。

**Comment by Heim12** [comment]
不推荐电脑控制。。PS2是最方便的选择了

**Comment by CharleyLiu** [comment]
PS2。。玩了三年表示熟悉的手感。。

**Comment by tripack45** [comment]
PS2 不是会信号穿线么= =而且有几组不是出现了PS2迷之连接不上和迷之断线的问题么
最好有个稳定性更好的解决方案

**Comment by CharleyLiu** [comment]
其实我觉得电脑不错。。。WASD感觉最符合人类。。

**Comment by tripack45** [comment]
电脑就是场上操作手不能太动，但是我们能做出一堆功能键，各种技能放得飞起

**Comment by CharleyLiu** [comment]
但是场地也不太大吧。。

**Comment by zyalll** [comment]
PS2 和 电脑操作还都挺符合人类习惯的  感觉用PAD之类操作精度会下降

**Comment by zhaoccjj** [comment]
PS2的L R耳朵键很好用.

发自我的 iPhone

**Comment by CharleyLiu** [comment]
PAD也不错。。。我感觉我这种玩各种奇葩游戏的没资格说啥好用。。。

**Comment by Heim12** [comment]
如果操作手没什么意见的话，电脑挺好……PS2断线我没遇到过，不过穿线倒是个大问题，估计学过工导的大部分会直接用PS2。机院那边似乎不会。。

**Comment by tripack45** [comment]
@zhaoccjj 你的引用是怎么点出来的= =不会啊

**Comment by zhaoccjj** [comment]
iPhone邮件里直接回复那个邮件.

发自PPxiaoPP的 iPhone

**Comment by CharleyLiu** [comment]
我直接开着了能实时更新很开心

**Comment by tripack45** [comment]
那要是用电脑的话= =蓝牙还是wifi？蓝牙稳定性差，但是代码好写，wifi的话还不知道要用啥硬件= =以及据说代码很难写= =要先搜索无线，然后连接，然后再开tcp/ip端口，什么socket之类的= =有人愿意去查一下嘛

**Comment by shuyang-huang** [comment]
这个问题可以缓缓再去解决的。我们现在应该解决的问题是机器人的进攻策略的问题吧。求数学大神来根绝判分标准进行一下数据分析。

**Comment by tripack45** [comment]
@Kinghsy 你又可以开issues了，赞
