### ISSUE TITLE
关于夹持式机械手

### ISSUE THREAD

**Issue by Heim12** [MICF-JI204/SocMain#35]
如图，材料用亚克力板。
两块带齿的（水平），两块夹板（竖直）。
水平板和竖直板之间如何连接固定待考虑。
![default](https://cloud.githubusercontent.com/assets/11556664/6765273/a107ffe2-d013-11e4-9066-0d14691dfeae.JPG)
夹板足够长（具体长度未定），一次性可以夹一排若干木块。
夹板的宽度（也就是侧视图中的高度）要和木块棱长差不多or再大一点。（舵机1的高度我画太大了）
整个夹持装置（图上除舵机2外的其他部件）用某种框架（待考虑）固定住，再连接到舵机2上。
夹的时候一边闭合两边的夹板（舵机1），一边转动整个夹持装置（舵机2），这样应该可以对付俯视图里编号1的那样摆放的木块（脑补的，待考证）。
两块夹板可以打开的角度很大，这样划过的面积也大，可以用来扫对方的木块。

问题：夹板之间如果木块比较多而且有垂直夹板排列的木块时，可能会卡住。(具体会怎么卡有点脑补不清楚)
PS.运动装置我觉得zcj那个很好

**Comment by tripack45** [comment]
以下复制一下群里的内容：这里还有一个设计
![6whp go40du 8gp2 3 y g](https://cloud.githubusercontent.com/assets/11572257/6765348/23fb14d6-d017-11e4-97db-ddbcd50dc6d6.png)
还能进一步实现4个的爪子，像抓娃娃机一样的设计。
缺点也很多，加持部分是个点接触，除非蜗杆锁很紧不然死活都不牢固，而且东西很难精确定位
理想的状况还是某种形式的固定盒和吸盘
一个矩形的框架大概固定位置上面一个吸盘

**Comment by zhaoccjj** [comment]
不需要自制蜗轮蜗杆机构实现直线运动，直线运动实现方法有很多，现成的小直线推杆电机就有.

发自PPxiaoPP的 iPhone

**Comment by tripack45** [comment]
@zhaoccjj 没有人再说直线运动啊= =还有为毛我淘宝上找不到小直线推杆的链接，求一个。
