### ISSUE TITLE
侧重于策略的一些想法

### ISSUE THREAD

**Issue by tripack45** [MICF-JI204/SocMain#36]
![1](https://cloud.githubusercontent.com/assets/11572257/6765885/bbbef7dc-d02c-11e4-9793-f928fd60d036.png)
上方是比赛的场地图。下面的数据半夜算得头疼，各位求帮忙查一下。
周日补充：特殊工件也计算倍数
基本的得分机制为：
**总得分=N1×20+N2×5+ N3*(N2+1)/2×10**
**其中 N1 为特殊工件价值，N2 为抢到对方的工件数量，N3为我方的竞争区数量**
注意到这个公式有以下特征：
1.如果没有抢得对方的工件，那么竞争区的工件价值和我方的得分区的价值一致。
2.每叠高一层将要导致竞争区的工件系数增加0.5，初始值是0.5
考虑到机器人的操作时间和运动速度，我认为：
1.从竞争区赶回得分区，再赶回竞争区，这个来回需要至少30秒
2.从竞争区抵达工件堆放区，在赶回竞争区，这个来回至少30秒
换言之，比赛时间一共3分钟，最多允许进行6个来回，实际情况下可能更少，因为发车区距离工件堆放区距离较远，同时操作也可能需要大量时间。不过在这里把6个来回作为极限情况考虑。
考虑几种情况：
1.完全没有抢得对方工件，我方工件打包丢在了竞争区，得分为190分。
2.完全没有抢得对方工件，我方工件打包丢在了竞争区，其中少了特殊工件，得分为170分。
3.采取一次从工件堆放区搬运一个工件到竞争区，6个来回，得分30（45,60）。
4.采取每个来回，从工件堆放区搬运1个工件到竞争区，每次回来带回一个对方普通工件，共计6个来回，叠到1层，得分(30+60)90分，考虑搬运去的有特殊工件，得分可能100或者110。对方按照2得分的话，计入140分。
5. 采取和4相同的策略，但是每次从我方搬运2个工件到竞争区，得分150分，已经超过对方。
6. 采取和4相同的策略，从对方竞争区抢夺得特殊工件一个（2个），得分100或者(110)，对方得分125（110），已经平手。
7. 考虑4的情况，每次从我方运送工件一个，将对方的普通工件叠到了2层高，没有特殊工件时，得分120，一个特殊工件得分135，2个特殊工件得分150。此处还不考虑抢夺得对方特殊工件。
7. 更可以考虑双方都带走对方工件的情况，但是基于上面的讨论这一讨论已经没有太大意义。
根据上方的分析发现
1.特殊工件对于游戏结果的影响巨大，应着重保护。
2.抢夺对方工件直接改变得分系数，即使稳扎稳打，每次搬运一个，拿走一个都能获得胜利。
3.工件的堆叠有效改变游戏结果。
根据以上的分析，提出一些建议：
1.同等时间下，抢夺对方工件效率高得多
2.不应将我方工件过早暴露在对方火力下
3.如果有可能，应尽可能快速大量的在后期向圆台倾倒工件
4.如果时间不足，应设法尽可能完成特殊工件任务
**5.同时特殊工件应尽可能晚得置于圆台之上**
**6.不应忽视每次只拿1个工件的设计，好的策略配上稳扎稳打的机器依然能获胜。**
**7.抢夺对方方块时，重要的是是否是特殊方块和堆叠**
因此提出以下策略
1. 一次性大量搬运和贮存方块的机构，一个方块盒子，比赛开始从工件堆放区取出足够数量的工件，贮存起来。应尽可能得取到特殊方块，但是如果不行，不应纠结。
2. 一个拾取单个方块，在机器内部进行堆叠的装置，就像是硬币自动分拣机那样，从圆台上拾取一个方块并且堆叠方块。在回到场地时将堆叠的方块放置在我方场地内。
3.一旦达成这个目标，剩余时间充沛回到工件堆放区，取出尽可能多的方块。
4.比赛快结束时，扫清对方较多圆台上的工件，将我方的工件堆叠与圆台上。
如果控制得当，此时对方手里不应有我方工件，在极限情况下，对方最大得分15×5+40=115分，在抢夺并堆叠对方一个工件的情况下，需要在圆台上放置12个工件即可获胜，在抢夺并堆叠2个工件的情况下，需要在圆台上放置8个工件即可获胜。
最后，考虑对方可能应对策略：
1.双方都不在圆台上放置工件，那么将会演化成比拼从金字塔中获得工件的能力的比赛，那么尽可能得搬走整个金字塔就很关键。
2.特殊情况没有考虑好。
机器具体设计暂时没有想好。

**Comment by CharleyLiu** [comment]
感觉内部堆叠不现实..我个人认为大部分队伍的策略都是：先不放，抢对面的，最后再放。
我觉得得想办法应对这种策略。
我目前想到的只能是拥有防守功能的小车..

**Comment by tripack45** [comment]
@CharleyLiu 对付这个的策略就是我们一口气比他们放更多的东西，因为我们不放置他们就抢不到，他们抢不到，要么闲着，要么就往台子上放东西。他们放东西了我们就能抢了，他们不放，如果他们没有在小车里设计一个预先堆放东西的地方，那么就是干等着不得分，而我们就可以往自己的盒子里预先丢东西，然后最后一股脑丢在台子上。

**Comment by zhaoccjj** [comment]
考虑到规则和策略，小车内存储木块，或者圆台旁事先堆叠木块很重要。
