### ISSUE TITLE
我又脑洞大开了，这次整合了拿木块方法和小车设计

### ISSUE THREAD

**Issue by CharleyLiu** [MICF-JI204/SocMain#37]
铛铛挡！~
挖掘机上场了~
咳咳。。
我这次目标是设计一个奇奇怪怪的东西，可以保证一开始不会往圆台上放工件，可以推掉对面的工件，又可以最后一秒放比对面多的多的工件。
怎么会有这么BUG的设计，一定特别复杂吧？
错，你需要的只是，挖掘机的，铲子。
![qq 20150322110454](https://cloud.githubusercontent.com/assets/10279946/6767860/88256660-d084-11e4-9e72-b917b3b51bc4.png)
![qq 20150322110459](https://cloud.githubusercontent.com/assets/10279946/6767863/92720ca4-d084-11e4-8c57-93a71062fbd3.png)

挖掘机的铲子分为大铲子小铲子两种，图里大的叫正铲，小的叫反铲。觉正铲的好用设计也更简单点。
某宝上这些铲子从大到小各种大小都有。
原则上最好小车在休息状态的时候铲子可以扣在小车上减少体积。但不知道这个设计会不会使得铲子强度不够或者使用的时候晃悠。。
![2222](https://cloud.githubusercontent.com/assets/10279946/6767877/58c85eb2-d085-11e4-992b-5b48494549e3.png)

感觉铲子上的钉耙 和前方的弧度正好可以用来铲起这些正方体。

以上

**Comment by zhaoccjj** [comment]
这个怎么没人评论？

**Comment by tripack45** [comment]
因为评论难度太大= =感觉主要是操作手的难度。
