### ISSUE TITLE
Assignments 2：To The Brand New Day

### ISSUE THREAD

**Issue by tripack45** [MICF-JI204/SocMain#42]
下一次开会的时间，周三晚9.15点。

这次的作业包括：
1. 以下的同学们需要在周五中午之前，完成一份有关项目的可行性报告：
a) 有关机械臂的可行性： @smice @Heim12 
b) 有关真空龙门吊的可行性 @CharleyLiu 
c) 有关叉车设计的可行性 @renll 
2. 关皮带设计的可行性
     @wzy199671  @zhaoccjj 
    同时还有车辆底盘的制作，周五due哦。
3.有关操作系统的设计 @Kinghsy 以及 @tripack45

首先，在这里我想对昨天的会议做出一些说明：
1）会议时间控制严重失当。这是我的锅，我知道自己不是一个特别会开会的人，时间控制上下次一定会调整，也会尽可能的减少开会的次数，以协调大家的时间表。同时希望大家能**上传一份课程表（时间表）（的截图）到本楼**以方便后面的时间安排。同时也希望大家多多包涵。
2）有小伙伴提出希望给出一份具体的TimeLine，不然显得心慌慌。我原来不给Timeline的原因不是我没有准备，而是觉得过笼统的timeline不能转化成具体的行动，因此放在那里徒增困惑，所以我尽量采取走一步看一步，每次开会确定下一个时间节点。不过，这份timeline最终决定还是上传吧，将会以Milestone的形式发表在Github上。想看的小伙伴欢迎翻页，欢迎指正。
3）还有很多细节的问题，等我体育课上完再更新吧。

对于各位的作业：什么样的文件是一份可行的 "Feasiblity Report"
各位未来的工导中并不会有一份这样的文件，然后Feasibility Report的形式，却会贯穿各位未来工导的**所有文件**，从Proposal 到 Progress Report。这里给出大家几点建议（要求）：
1）文件里要有什么？
 答案很简单，所有的有必要的，用于向别人说明，为什么某个方案可行（不可行）的内容。这些内容包括但是不限于（远不止）：这个结构需要几个电机？每个电机大概需要多强力？电机有地方放吗？需要什么机械?如果要抬升，抬升装置用结构做？具体怎么设计？稳不稳？对小车重心有没有影响……尤其是要注意的是，不要把”这个总归很简单“或者”我不考虑了，这个反正有很多方法可以实现“作为任何一个问题的答案。因为这些答案往往意味着你不知道怎么办，而你不知道怎么办的原因，往往是并没有一个简单可行的方案。同时，就算一个方案有很多种实现，你的任务也包含了确定其中一种实现。
2）文件里的图？
推荐各位使用Exploded View：
![hot-chamber-die-exploded](https://cloud.githubusercontent.com/assets/11572257/6774397/86b727f6-d15a-11e4-852c-9a362dfc523d.png)
以上是一个Exploded View 的样张，其中精髓请自行领会。
3）我有一部分不会？
很正常，这时候请把你的问题整理一下，发一个Issue。你需要别人的帮助。有的时候你不太清楚你之所以设计不出来是方案本身的问题，还是有好方法没有想到。所以，经过思考，如果没有什么好的主意，请尝试 Bring In More People，请不要浪费一个很好的Idea，每个Idea都尤为重要。

关于做底盘的小组，我建议你们底盘采用3mm厚度的亚克力板，因为方便切割。但是强度不足，所以可能需要一些辅助的结构件。这里给出各位几个螃蟹王国的diy材料链接。这些材料因为被设计用于diy这样的东西的：
![default](https://cloud.githubusercontent.com/assets/11572257/6774520/c1f288ae-d15c-11e4-9c6c-a18a1197f6fb.JPG)

一些可能小零件：
塑料条：http://detail.tmall.com/item.htm?spm=a1z10.5-b.w4011-2934102283.111.WpRw85&id=37110358889&rn=06a3b397427cf79faad32041bcdd60ea&abbucket=19
角件：http://detail.tmall.com/item.htm?spm=a1z10.5-b.w4011-2934102283.121.ZhmRKL&id=37127956334&rn=02a59400d58dbc457d04aa6245d8c055&abbucket=19
其他的还请自行翻阅。考虑到我们车身比较重，甚至可以适当考虑使用铝材。我依然推荐使用一些比较高强度材料来搭框架，保证结构稳定的。

最后，每天一刷github不止要求各位看，更重要的是要写。要写Issue，要回Issue，无论你所写的内容脑洞有多大，方案多不成熟，说出来我们一起完善，有价值的思想往往来自这些过程。我希望能鼓励新的观点，因为我需要所有人的观点来对抗一意孤行的执念。所以请小伙伴们务必保证每天写（回）一份Github。

以上。
@tripack45

**Comment by CharleyLiu** [comment]
__I am Bold__

**Comment by renll** [comment]
等一下，周三晚6：00～9：00有化学实验，会议最好改到9：30

**Comment by tripack45** [comment]
如果没有人有化学实验课的话我时间就不动了了。

**Comment by Heim12** [comment]
RLL是周三晚的吧

**Comment by zhaoccjj** [comment]
名字里都带LL，果然厉害👍

发自PPxiaoPP的 iPhone

**Comment by tripack45** [comment]
@zhaoccjj 你怎么不说名字里带RL

**Comment by CharleyLiu** [comment]
![2](https://cloud.githubusercontent.com/assets/10279946/6775454/59d2f028-d16c-11e4-9b01-d0b3fbef6b0a.png)

撒花~鼓掌~我周三没有课~周四全是课~ 周五外帝汪回不去家。。。
**-------------------------------------分割线的我又出现了-----------------------------------------------------------------**

**Comment by renll** [comment]
所以我的意思是我周三晚上有化学实验课，会议请改到p.m.9:30啊_(:3」∠)_

**Comment by renll** [comment]
LL是什么，可以吃么？（笑

**Comment by zyalll** [comment]
![screenshot_2015-03-23-16-15-43](https://cloud.githubusercontent.com/assets/11556422/6776326/1cb593ec-d178-11e4-8bbd-8d90d47f524c.png)
周四下午有思修+化学实验0.0

**Comment by shuyang-huang** [comment]
我的课时和LC一样的可以安排。

**Comment by smice** [comment]
![default](https://cloud.githubusercontent.com/assets/11556838/6779352/155af1e6-d196-11e4-8e03-e482f2074b05.png)
