### ISSUE TITLE
补一下昨晚关于小车设计的BUG脑洞，变形小车的可行性分析（伪）

### ISSUE THREAD

**Issue by CharleyLiu** [MICF-JI204/SocMain#47]
如果我们有一辆小车，可以同时对两个圆台进行控制，似乎很厉害的样子。
问题是技术上小车或者机械臂不太好做那么长。
那有没有低（黑）科技的替代方案。
答案是有的。
假设小车是圆形的
![img_1766](https://cloud.githubusercontent.com/assets/10279946/6816695/980cc646-d2d1-11e4-88f1-8312488f3ec3.JPG)

中间的黑科技是一个弹簧杆，在不触发时候是一个很短很结实的内部构件。触发后迅速弹出，弹成不可缩短，较长的一根长杆（CITE 雨伞的伞骨或者魔术棒或者教鞭）。两个圆台相距0.7M，应该还是比较好达到的。

同时小车左右各安排一块arduino，上面假设有两个机械臂，然后两个操作员一个人玩一部分小车专心玩自己的圆台。

比赛时的策略是先在木块堆放区拿取足够多的木块，然后前进到圆台中间，弹开，丧失运动能力，专心对两个圆台控制。
所得的结果是对小车的运动能力要求不高，小车上的工件相关功能以模块的方式安装上去。
比如每个人都有一个吹风机加一个可以大量抓取的东西0.0.。。虽然很假但是画面好美。。。

**说下想这个的原因吧。我觉得所有组都一定会竭力避免对方拿走自己的木块，甚至是不惜以自己不放木块不得分为代价。所以不如放弃这块功能，剑走偏锋，以保证圆台上我方木块比对方多即可。**

唯一想到的不足是小车底盘的运动功能设计比较费劲。我建议是仍然保证是两个轮子由一个人控制。但能否在变形时中间的接线不影响变形（比如预先准备好足够长的线团好放在内部）。
说实话，这个小车的设计不像小车了，更像一个流水线工作机器人（CITE我魔性的大脑）

![img_1767](https://cloud.githubusercontent.com/assets/10279946/6816833/53686958-d2d3-11e4-9f67-f584627abbe9.JPG)

假想图，感觉配合我昨天关于真空吸的设计其实不错。给予了机械臂拿多个木块的可能性

**Comment by smice** [comment]
不过好奇，轮子怎么办？还是那样两个轮子两个滚珠吗？还是再多加一对支撑的东西？

**Comment by CharleyLiu** [comment]
我孤陋寡闻没法很好处理轮子的问题。。。。

**Comment by Heim12** [comment]
弹开后不要求小车再运动了吧，轮子可以在之前zcj设计的基础上多加两个滚珠/万向轮，分开之后一边一个轮子二个滚珠，三角支撑

**Comment by zyalll** [comment]
很有创意啊~
不过我想问几点问题。
1，如果分开后位置不合适怎么办？GG 
2，就算分开后位置合适，我如何保证我的操作一定比对面牛逼一定能毫无漏洞？ 
假设你已经拿到一半的木块  （我觉得这已经是个很大的数字了）你得到90分
而对面假设拿了你两个木块，这样人家放5个即可。
你需要同时注意18个木块，对面的操作难度小的多。 而且拿木块的难度是小于防守难度的，因为拿木块是主动方，在那么多木块可以拿的情况下防守方会手忙脚乱。
其次，就算对面拿不到木块，对面对圆台实行类似于扫荡的破坏性措施，我们受到的损失远远大于对方。
一个木块抢不到和抢到一个木块相比，双方圆台木块得分难易程度直接相差一倍。因此，”只“保证我方圆台上木块比对方的多并不是一个很好的策略。
（当然这个只是我的个人想法，如果LC说我能保证以我精妙的微操打的对面直接GG，这个就不成问题了）
3，当分开后，是不是需要固定在地上？
不然的话由于牛三，抢夺木块过程中两个“炮台”会向后退的。而小车又丧失了运动能力，位置的改变会对策略造成影响。

**Comment by CharleyLiu** [comment]
回答1，可能要靠机械臂的灵活度去弥补。而且也许并不是不能动。。
回答2，我这个剑走偏锋的设计原因就是对面只能控制一个台子，所以我们对对面控制的台子实行进攻的破坏措施，吹下去啊打下去啊之类的。另一个台子咱们放自己的物块。当然这些都会在比赛后期让对面来不及反应。
并非同时注意多个木块，可以先不拿上去让对面碰不到即可。
回答3，可以做一个敦厚的行动缓慢的小车，因为这个设计剑走偏锋只需要在堆放区和圆台间走一次并且并不需要赶时间，可以放好多铁块啥的走慢点但是让车体变重。
