### ISSUE TITLE
机械手分析 

### ISSUE THREAD

**Issue by Heim12** [MICF-JI204/SocMain#49]
手贱关了浏览器。。全部重新码TAT，我就简单写写好了，开会细讲。
-------------------------------分--------------------------------------------------------------
多文字，感觉用图片不大能帮助理解，不如开会的时候演示。
-------------------------------分--------------------------------------------------------------
可选自由度/转动部位：
1) 手掌抓取：抓木块
2) 手腕转动：稳定木块
3) 手腕左右/上下摆动：减少小车移动任务/配合自由度6)
4) 手臂伸缩：减小整车长度
5) 手臂整体抬升：应对圆台
6) 手肘转动：手关节初始高度和圆台相同，夹地面上木块时转动降低手的高度，配合自由度3)上下摆动调整手的角度
1236用舵机，4参考链接，5暂时没有好想法
http://item.taobao.com/item.htm?spm=2013.1.0.0.X4caIS&id=43147988060
-------------------------------分--------------------------------------------------------------
抓取方式：
1. 直接抓取
2. 边抓边旋转手腕
-------------------------------分--------------------------------------------------------------
一次性抓取木块数量：
(1) 单个抓取：
改进：手掌内侧贴皮带/软性材料，增加摩擦；手掌做成圆弧型/关节型。

(2) 多个同一平面：
改进：加长手掌来扩大抓取范围，采用抓取方式2，直线/波浪型手掌
优势：木块抓得多；可以用来扫木块
劣势：手掌加长，末端稳定性差，而针对靠近墙的木块只能用末端抓取；有一个木块对角线卡住手掌后，转动手腕时其他木块可能掉出来。

(3) 多个堆叠：
实验的机械手可以勉强抓起两个堆叠的木块。
改进：加宽手掌，防止上层木块滑落；增加掌内与木块的摩擦系数
优势：方便叠高
劣势：一次性拿得少
-------------------------------分--------------------------------------------------------------
关于墙角的问题：
如果真的卡死在墙角，普通机械手无能为力，只能用刀片挖出来。
可以考虑在掌尖加刀片O_o

**Comment by smice** [comment]
我想到一点，可不可以在小车上装一个偏心轮，利用夯土机的原理来先把木块震震松？

**Comment by CharleyLiu** [comment]
手背/爪背也装上一些高摩擦性的东西然后拨出来？

**Comment by Heim12** [comment]
对的，目前准备爪背加皮带之类的来拨木块
