### ISSUE TITLE
机械手分析·改

### ISSUE THREAD

**Issue by smice** [MICF-JI204/SocMain#54]
在宜修上一篇机械手分析的基础上的确定设计。

那篇一共讲了6个自由度。我们把它精简成了3个，分别为：机械臂和车体的连接-上下摆动；机械臂和机械手的连接-左右转动；爪子的开合。

材料我们打算采取的是亚克力板。

下图为整个机械臂+机械手的侧视图
![1427630028403](https://cloud.githubusercontent.com/assets/11556838/6885483/b2ae8b84-d654-11e4-8994-03e763906231.jpg)
下图为从上往下看的俯视图
![1427630698934](https://cloud.githubusercontent.com/assets/11556838/6885488/c5477d3c-d654-11e4-8d3d-0817012e9b9c.jpg)

分解图：

手肘：
![1427631477750](https://cloud.githubusercontent.com/assets/11556838/6885490/e39356da-d654-11e4-9c82-01942d275d65.jpg)

手腕：
![1427632120051](https://cloud.githubusercontent.com/assets/11556838/6885508/43daf3fe-d655-11e4-9b57-74df8fd621ff.jpg)

以及手腕和手臂的之间有垂直连接，现拟采用角片的刚性连接。
角片应该是很牢固的，淘宝上很多，我们还没有特定哪个好的比较过。

然后，一些出现的问题解答：
1、有关父issue里面对卡死在墙角，普通机械手无能为力的问题，是可以用皮条粘在外侧拨出来就可以了，亲测有效。
2、有关只有三个自由度，当夹取地面物体时会指尖朝下斜着夹，是否可以依然夹取一个，上面叠一个的类型，亲测可以。
3、有关夹取地面木块时，手腕转动，导致两片爪子一高一低诡异的倾斜（就是爪子的平面不和木块几个面的三个平面的任意一个平行），但是不影响抓取（试过了，但是一次抓两个就估计不行），特别是我们还要在爪子内侧加软性材料。

that's all.

**Comment by CharleyLiu** [comment]
标重力方向的都是好人

**Comment by Heim12** [comment]
给结构图赞一个，你确定第二幅图里写的是亚克力不是巧克力？

**Comment by smice** [comment]
@Heim12 我确定我写的是巧克力、。。。
